/**
 * CONFIGURATION STRICTE DES ACTIFS DE TRADING
 * ============================================
 * Chaque actif doit avoir une configuration explicite.
 * INTERDICTION ABSOLUE d'utiliser des valeurs génériques ou supposées.
 */

export type AssetType = 
  | 'forex_non_jpy'
  | 'forex_jpy'
  | 'metal_gold'
  | 'metal_silver'
  | 'metal_platinum'
  | 'index_us'
  | 'index_eu'
  | 'index_asia'
  | 'crypto_major'
  | 'crypto_alt'
  | 'energy'
  | 'stock';

export type RoundingMode = 'DOWN' | 'HALF_UP';

export interface AssetConfig {
  symbol: string;
  assetType: AssetType;
  priceDecimals: number;        // Nombre de décimales du prix (ex: 5 pour EURUSD)
  pipSize: number;              // Taille d'un pip (ex: 0.0001 pour EURUSD)
  tickSize: number;             // Plus petite variation de prix
  contractSize: number;         // Taille du contrat pour 1 lot standard
  minLot: number;               // Lot minimum tradable
  maxLot: number;               // Lot maximum tradable
  lotStep: number;              // Incrément de lot
  quoteCurrency: string;        // Devise de cotation
  baseCurrency?: string;        // Devise de base (pour forex)
  roundingMode: RoundingMode;   // Mode d'arrondi pour les lots
}

// ============================================================================
// CONFIGURATIONS FOREX NON-JPY
// pip_size = 0.0001, price_decimals = 5, contract_size = 100,000
// ============================================================================
const FOREX_NON_JPY_CONFIG: Partial<AssetConfig> = {
  assetType: 'forex_non_jpy',
  priceDecimals: 5,
  pipSize: 0.0001,
  tickSize: 0.00001,
  contractSize: 100000,
  minLot: 0.01,
  maxLot: 100,
  lotStep: 0.01,
  roundingMode: 'DOWN',
};

// ============================================================================
// CONFIGURATIONS FOREX JPY
// pip_size = 0.01, price_decimals = 3, contract_size = 100,000
// ============================================================================
const FOREX_JPY_CONFIG: Partial<AssetConfig> = {
  assetType: 'forex_jpy',
  priceDecimals: 3,
  pipSize: 0.01,
  tickSize: 0.001,
  contractSize: 100000,
  minLot: 0.01,
  maxLot: 100,
  lotStep: 0.01,
  roundingMode: 'DOWN',
};

// ============================================================================
// BASE DE DONNÉES DES ACTIFS
// ============================================================================
export const ASSET_CONFIGS: Record<string, AssetConfig> = {
  // FOREX MAJORS (Non-JPY)
  'EUR/USD': { ...FOREX_NON_JPY_CONFIG, symbol: 'EUR/USD', baseCurrency: 'EUR', quoteCurrency: 'USD' } as AssetConfig,
  'GBP/USD': { ...FOREX_NON_JPY_CONFIG, symbol: 'GBP/USD', baseCurrency: 'GBP', quoteCurrency: 'USD' } as AssetConfig,
  'AUD/USD': { ...FOREX_NON_JPY_CONFIG, symbol: 'AUD/USD', baseCurrency: 'AUD', quoteCurrency: 'USD' } as AssetConfig,
  'NZD/USD': { ...FOREX_NON_JPY_CONFIG, symbol: 'NZD/USD', baseCurrency: 'NZD', quoteCurrency: 'USD' } as AssetConfig,
  'USD/CAD': { ...FOREX_NON_JPY_CONFIG, symbol: 'USD/CAD', baseCurrency: 'USD', quoteCurrency: 'CAD' } as AssetConfig,
  'USD/CHF': { ...FOREX_NON_JPY_CONFIG, symbol: 'USD/CHF', baseCurrency: 'USD', quoteCurrency: 'CHF' } as AssetConfig,
  
  // FOREX JPY PAIRS
  'USD/JPY': { ...FOREX_JPY_CONFIG, symbol: 'USD/JPY', baseCurrency: 'USD', quoteCurrency: 'JPY' } as AssetConfig,
  'EUR/JPY': { ...FOREX_JPY_CONFIG, symbol: 'EUR/JPY', baseCurrency: 'EUR', quoteCurrency: 'JPY' } as AssetConfig,
  'GBP/JPY': { ...FOREX_JPY_CONFIG, symbol: 'GBP/JPY', baseCurrency: 'GBP', quoteCurrency: 'JPY' } as AssetConfig,
  'AUD/JPY': { ...FOREX_JPY_CONFIG, symbol: 'AUD/JPY', baseCurrency: 'AUD', quoteCurrency: 'JPY' } as AssetConfig,
  'CAD/JPY': { ...FOREX_JPY_CONFIG, symbol: 'CAD/JPY', baseCurrency: 'CAD', quoteCurrency: 'JPY' } as AssetConfig,
  'CHF/JPY': { ...FOREX_JPY_CONFIG, symbol: 'CHF/JPY', baseCurrency: 'CHF', quoteCurrency: 'JPY' } as AssetConfig,
  'NZD/JPY': { ...FOREX_JPY_CONFIG, symbol: 'NZD/JPY', baseCurrency: 'NZD', quoteCurrency: 'JPY' } as AssetConfig,
  
  // FOREX CROSSES (Non-JPY)
  'EUR/GBP': { ...FOREX_NON_JPY_CONFIG, symbol: 'EUR/GBP', baseCurrency: 'EUR', quoteCurrency: 'GBP' } as AssetConfig,
  'EUR/CHF': { ...FOREX_NON_JPY_CONFIG, symbol: 'EUR/CHF', baseCurrency: 'EUR', quoteCurrency: 'CHF' } as AssetConfig,
  'EUR/AUD': { ...FOREX_NON_JPY_CONFIG, symbol: 'EUR/AUD', baseCurrency: 'EUR', quoteCurrency: 'AUD' } as AssetConfig,
  'EUR/CAD': { ...FOREX_NON_JPY_CONFIG, symbol: 'EUR/CAD', baseCurrency: 'EUR', quoteCurrency: 'CAD' } as AssetConfig,
  'EUR/NZD': { ...FOREX_NON_JPY_CONFIG, symbol: 'EUR/NZD', baseCurrency: 'EUR', quoteCurrency: 'NZD' } as AssetConfig,
  'GBP/CHF': { ...FOREX_NON_JPY_CONFIG, symbol: 'GBP/CHF', baseCurrency: 'GBP', quoteCurrency: 'CHF' } as AssetConfig,
  'GBP/AUD': { ...FOREX_NON_JPY_CONFIG, symbol: 'GBP/AUD', baseCurrency: 'GBP', quoteCurrency: 'AUD' } as AssetConfig,
  'GBP/CAD': { ...FOREX_NON_JPY_CONFIG, symbol: 'GBP/CAD', baseCurrency: 'GBP', quoteCurrency: 'CAD' } as AssetConfig,
  'GBP/NZD': { ...FOREX_NON_JPY_CONFIG, symbol: 'GBP/NZD', baseCurrency: 'GBP', quoteCurrency: 'NZD' } as AssetConfig,
  'AUD/CAD': { ...FOREX_NON_JPY_CONFIG, symbol: 'AUD/CAD', baseCurrency: 'AUD', quoteCurrency: 'CAD' } as AssetConfig,
  'AUD/CHF': { ...FOREX_NON_JPY_CONFIG, symbol: 'AUD/CHF', baseCurrency: 'AUD', quoteCurrency: 'CHF' } as AssetConfig,
  'AUD/NZD': { ...FOREX_NON_JPY_CONFIG, symbol: 'AUD/NZD', baseCurrency: 'AUD', quoteCurrency: 'NZD' } as AssetConfig,
  'CAD/CHF': { ...FOREX_NON_JPY_CONFIG, symbol: 'CAD/CHF', baseCurrency: 'CAD', quoteCurrency: 'CHF' } as AssetConfig,
  'NZD/CAD': { ...FOREX_NON_JPY_CONFIG, symbol: 'NZD/CAD', baseCurrency: 'NZD', quoteCurrency: 'CAD' } as AssetConfig,
  'NZD/CHF': { ...FOREX_NON_JPY_CONFIG, symbol: 'NZD/CHF', baseCurrency: 'NZD', quoteCurrency: 'CHF' } as AssetConfig,
  
  // FOREX EXOTICS
  'USD/TRY': { ...FOREX_NON_JPY_CONFIG, symbol: 'USD/TRY', baseCurrency: 'USD', quoteCurrency: 'TRY' } as AssetConfig,
  'USD/MXN': { ...FOREX_NON_JPY_CONFIG, symbol: 'USD/MXN', baseCurrency: 'USD', quoteCurrency: 'MXN' } as AssetConfig,
  'USD/ZAR': { ...FOREX_NON_JPY_CONFIG, symbol: 'USD/ZAR', baseCurrency: 'USD', quoteCurrency: 'ZAR' } as AssetConfig,
  'USD/SGD': { ...FOREX_NON_JPY_CONFIG, symbol: 'USD/SGD', baseCurrency: 'USD', quoteCurrency: 'SGD' } as AssetConfig,
  'USD/HKD': { ...FOREX_NON_JPY_CONFIG, symbol: 'USD/HKD', baseCurrency: 'USD', quoteCurrency: 'HKD' } as AssetConfig,
  'USD/NOK': { ...FOREX_NON_JPY_CONFIG, symbol: 'USD/NOK', baseCurrency: 'USD', quoteCurrency: 'NOK' } as AssetConfig,
  'USD/SEK': { ...FOREX_NON_JPY_CONFIG, symbol: 'USD/SEK', baseCurrency: 'USD', quoteCurrency: 'SEK' } as AssetConfig,
  'USD/DKK': { ...FOREX_NON_JPY_CONFIG, symbol: 'USD/DKK', baseCurrency: 'USD', quoteCurrency: 'DKK' } as AssetConfig,
  'USD/PLN': { ...FOREX_NON_JPY_CONFIG, symbol: 'USD/PLN', baseCurrency: 'USD', quoteCurrency: 'PLN' } as AssetConfig,
  'USD/HUF': { ...FOREX_NON_JPY_CONFIG, symbol: 'USD/HUF', baseCurrency: 'USD', quoteCurrency: 'HUF', priceDecimals: 3, pipSize: 0.01 } as AssetConfig,
  'USD/CZK': { ...FOREX_NON_JPY_CONFIG, symbol: 'USD/CZK', baseCurrency: 'USD', quoteCurrency: 'CZK' } as AssetConfig,
  'EUR/TRY': { ...FOREX_NON_JPY_CONFIG, symbol: 'EUR/TRY', baseCurrency: 'EUR', quoteCurrency: 'TRY' } as AssetConfig,
  'EUR/NOK': { ...FOREX_NON_JPY_CONFIG, symbol: 'EUR/NOK', baseCurrency: 'EUR', quoteCurrency: 'NOK' } as AssetConfig,
  'EUR/SEK': { ...FOREX_NON_JPY_CONFIG, symbol: 'EUR/SEK', baseCurrency: 'EUR', quoteCurrency: 'SEK' } as AssetConfig,
  'EUR/PLN': { ...FOREX_NON_JPY_CONFIG, symbol: 'EUR/PLN', baseCurrency: 'EUR', quoteCurrency: 'PLN' } as AssetConfig,
  'EUR/HUF': { ...FOREX_NON_JPY_CONFIG, symbol: 'EUR/HUF', baseCurrency: 'EUR', quoteCurrency: 'HUF', priceDecimals: 3, pipSize: 0.01 } as AssetConfig,
  'GBP/TRY': { ...FOREX_NON_JPY_CONFIG, symbol: 'GBP/TRY', baseCurrency: 'GBP', quoteCurrency: 'TRY' } as AssetConfig,
  'GBP/NOK': { ...FOREX_NON_JPY_CONFIG, symbol: 'GBP/NOK', baseCurrency: 'GBP', quoteCurrency: 'NOK' } as AssetConfig,
  'GBP/SEK': { ...FOREX_NON_JPY_CONFIG, symbol: 'GBP/SEK', baseCurrency: 'GBP', quoteCurrency: 'SEK' } as AssetConfig,
  'GBP/ZAR': { ...FOREX_NON_JPY_CONFIG, symbol: 'GBP/ZAR', baseCurrency: 'GBP', quoteCurrency: 'ZAR' } as AssetConfig,
  
  // MÉTAUX PRÉCIEUX
  'XAU/USD': {
    symbol: 'XAU/USD',
    assetType: 'metal_gold',
    priceDecimals: 2,
    pipSize: 0.01,
    tickSize: 0.01,
    contractSize: 100, // 100 onces
    minLot: 0.01,
    maxLot: 50,
    lotStep: 0.01,
    quoteCurrency: 'USD',
    baseCurrency: 'XAU',
    roundingMode: 'DOWN',
  },
  'XAG/USD': {
    symbol: 'XAG/USD',
    assetType: 'metal_silver',
    priceDecimals: 3,
    pipSize: 0.001,
    tickSize: 0.001,
    contractSize: 5000, // 5000 onces
    minLot: 0.01,
    maxLot: 50,
    lotStep: 0.01,
    quoteCurrency: 'USD',
    baseCurrency: 'XAG',
    roundingMode: 'DOWN',
  },
  'XPT/USD': {
    symbol: 'XPT/USD',
    assetType: 'metal_platinum',
    priceDecimals: 2,
    pipSize: 0.01,
    tickSize: 0.01,
    contractSize: 100,
    minLot: 0.01,
    maxLot: 50,
    lotStep: 0.01,
    quoteCurrency: 'USD',
    baseCurrency: 'XPT',
    roundingMode: 'DOWN',
  },
  'XPD/USD': {
    symbol: 'XPD/USD',
    assetType: 'metal_platinum',
    priceDecimals: 2,
    pipSize: 0.01,
    tickSize: 0.01,
    contractSize: 100,
    minLot: 0.01,
    maxLot: 50,
    lotStep: 0.01,
    quoteCurrency: 'USD',
    baseCurrency: 'XPD',
    roundingMode: 'DOWN',
  },
  'COPPER': {
    symbol: 'COPPER',
    assetType: 'metal_platinum',
    priceDecimals: 4,
    pipSize: 0.0001,
    tickSize: 0.0001,
    contractSize: 25000,
    minLot: 0.01,
    maxLot: 50,
    lotStep: 0.01,
    quoteCurrency: 'USD',
    roundingMode: 'DOWN',
  },
  
  // INDICES US
  'US30': {
    symbol: 'US30',
    assetType: 'index_us',
    priceDecimals: 0,
    pipSize: 1,
    tickSize: 1,
    contractSize: 1, // 1$ per point
    minLot: 0.1,
    maxLot: 100,
    lotStep: 0.1,
    quoteCurrency: 'USD',
    roundingMode: 'DOWN',
  },
  'US100': {
    symbol: 'US100',
    assetType: 'index_us',
    priceDecimals: 1,
    pipSize: 0.1,
    tickSize: 0.1,
    contractSize: 1,
    minLot: 0.1,
    maxLot: 100,
    lotStep: 0.1,
    quoteCurrency: 'USD',
    roundingMode: 'DOWN',
  },
  'US500': {
    symbol: 'US500',
    assetType: 'index_us',
    priceDecimals: 1,
    pipSize: 0.1,
    tickSize: 0.1,
    contractSize: 10, // 10$ per point
    minLot: 0.1,
    maxLot: 100,
    lotStep: 0.1,
    quoteCurrency: 'USD',
    roundingMode: 'DOWN',
  },
  'US2000': {
    symbol: 'US2000',
    assetType: 'index_us',
    priceDecimals: 1,
    pipSize: 0.1,
    tickSize: 0.1,
    contractSize: 1,
    minLot: 0.1,
    maxLot: 100,
    lotStep: 0.1,
    quoteCurrency: 'USD',
    roundingMode: 'DOWN',
  },
  'VIX': {
    symbol: 'VIX',
    assetType: 'index_us',
    priceDecimals: 2,
    pipSize: 0.01,
    tickSize: 0.01,
    contractSize: 100,
    minLot: 0.1,
    maxLot: 100,
    lotStep: 0.1,
    quoteCurrency: 'USD',
    roundingMode: 'DOWN',
  },
  
  // INDICES EUROPE
  'GER40': {
    symbol: 'GER40',
    assetType: 'index_eu',
    priceDecimals: 1,
    pipSize: 0.1,
    tickSize: 0.1,
    contractSize: 1,
    minLot: 0.1,
    maxLot: 100,
    lotStep: 0.1,
    quoteCurrency: 'EUR',
    roundingMode: 'DOWN',
  },
  'UK100': {
    symbol: 'UK100',
    assetType: 'index_eu',
    priceDecimals: 1,
    pipSize: 0.1,
    tickSize: 0.1,
    contractSize: 1,
    minLot: 0.1,
    maxLot: 100,
    lotStep: 0.1,
    quoteCurrency: 'GBP',
    roundingMode: 'DOWN',
  },
  'FRA40': {
    symbol: 'FRA40',
    assetType: 'index_eu',
    priceDecimals: 1,
    pipSize: 0.1,
    tickSize: 0.1,
    contractSize: 1,
    minLot: 0.1,
    maxLot: 100,
    lotStep: 0.1,
    quoteCurrency: 'EUR',
    roundingMode: 'DOWN',
  },
  'SPA35': {
    symbol: 'SPA35',
    assetType: 'index_eu',
    priceDecimals: 0,
    pipSize: 1,
    tickSize: 1,
    contractSize: 1,
    minLot: 0.1,
    maxLot: 100,
    lotStep: 0.1,
    quoteCurrency: 'EUR',
    roundingMode: 'DOWN',
  },
  'ITA40': {
    symbol: 'ITA40',
    assetType: 'index_eu',
    priceDecimals: 0,
    pipSize: 1,
    tickSize: 1,
    contractSize: 1,
    minLot: 0.1,
    maxLot: 100,
    lotStep: 0.1,
    quoteCurrency: 'EUR',
    roundingMode: 'DOWN',
  },
  'EU50': {
    symbol: 'EU50',
    assetType: 'index_eu',
    priceDecimals: 1,
    pipSize: 0.1,
    tickSize: 0.1,
    contractSize: 1,
    minLot: 0.1,
    maxLot: 100,
    lotStep: 0.1,
    quoteCurrency: 'EUR',
    roundingMode: 'DOWN',
  },
  'SUI20': {
    symbol: 'SUI20',
    assetType: 'index_eu',
    priceDecimals: 0,
    pipSize: 1,
    tickSize: 1,
    contractSize: 1,
    minLot: 0.1,
    maxLot: 100,
    lotStep: 0.1,
    quoteCurrency: 'CHF',
    roundingMode: 'DOWN',
  },
  'NED25': {
    symbol: 'NED25',
    assetType: 'index_eu',
    priceDecimals: 2,
    pipSize: 0.01,
    tickSize: 0.01,
    contractSize: 1,
    minLot: 0.1,
    maxLot: 100,
    lotStep: 0.1,
    quoteCurrency: 'EUR',
    roundingMode: 'DOWN',
  },
  
  // INDICES ASIE
  'JPN225': {
    symbol: 'JPN225',
    assetType: 'index_asia',
    priceDecimals: 0,
    pipSize: 1,
    tickSize: 1,
    contractSize: 100, // 100 JPY per point
    minLot: 0.1,
    maxLot: 100,
    lotStep: 0.1,
    quoteCurrency: 'JPY',
    roundingMode: 'DOWN',
  },
  'HK50': {
    symbol: 'HK50',
    assetType: 'index_asia',
    priceDecimals: 0,
    pipSize: 1,
    tickSize: 1,
    contractSize: 1,
    minLot: 0.1,
    maxLot: 100,
    lotStep: 0.1,
    quoteCurrency: 'HKD',
    roundingMode: 'DOWN',
  },
  'AUS200': {
    symbol: 'AUS200',
    assetType: 'index_asia',
    priceDecimals: 1,
    pipSize: 0.1,
    tickSize: 0.1,
    contractSize: 1,
    minLot: 0.1,
    maxLot: 100,
    lotStep: 0.1,
    quoteCurrency: 'AUD',
    roundingMode: 'DOWN',
  },
  'CHINA50': {
    symbol: 'CHINA50',
    assetType: 'index_asia',
    priceDecimals: 1,
    pipSize: 0.1,
    tickSize: 0.1,
    contractSize: 1,
    minLot: 0.1,
    maxLot: 100,
    lotStep: 0.1,
    quoteCurrency: 'USD',
    roundingMode: 'DOWN',
  },
  'SGP20': {
    symbol: 'SGP20',
    assetType: 'index_asia',
    priceDecimals: 1,
    pipSize: 0.1,
    tickSize: 0.1,
    contractSize: 1,
    minLot: 0.1,
    maxLot: 100,
    lotStep: 0.1,
    quoteCurrency: 'SGD',
    roundingMode: 'DOWN',
  },
  'INDIA50': {
    symbol: 'INDIA50',
    assetType: 'index_asia',
    priceDecimals: 1,
    pipSize: 0.1,
    tickSize: 0.1,
    contractSize: 1,
    minLot: 0.1,
    maxLot: 100,
    lotStep: 0.1,
    quoteCurrency: 'INR',
    roundingMode: 'DOWN',
  },
  
  // CRYPTO MAJORS
  'BTC/USD': {
    symbol: 'BTC/USD',
    assetType: 'crypto_major',
    priceDecimals: 2,
    pipSize: 1, // 1 point = 1 USD
    tickSize: 0.01,
    contractSize: 1, // 1 BTC
    minLot: 0.01,
    maxLot: 10,
    lotStep: 0.01,
    quoteCurrency: 'USD',
    baseCurrency: 'BTC',
    roundingMode: 'DOWN',
  },
  'ETH/USD': {
    symbol: 'ETH/USD',
    assetType: 'crypto_major',
    priceDecimals: 2,
    pipSize: 0.1,
    tickSize: 0.01,
    contractSize: 1,
    minLot: 0.01,
    maxLot: 100,
    lotStep: 0.01,
    quoteCurrency: 'USD',
    baseCurrency: 'ETH',
    roundingMode: 'DOWN',
  },
  'BNB/USD': {
    symbol: 'BNB/USD',
    assetType: 'crypto_major',
    priceDecimals: 2,
    pipSize: 0.1,
    tickSize: 0.01,
    contractSize: 1,
    minLot: 0.1,
    maxLot: 1000,
    lotStep: 0.1,
    quoteCurrency: 'USD',
    baseCurrency: 'BNB',
    roundingMode: 'DOWN',
  },
  'XRP/USD': {
    symbol: 'XRP/USD',
    assetType: 'crypto_alt',
    priceDecimals: 4,
    pipSize: 0.0001,
    tickSize: 0.0001,
    contractSize: 100,
    minLot: 1,
    maxLot: 10000,
    lotStep: 1,
    quoteCurrency: 'USD',
    baseCurrency: 'XRP',
    roundingMode: 'DOWN',
  },
  'SOL/USD': {
    symbol: 'SOL/USD',
    assetType: 'crypto_major',
    priceDecimals: 2,
    pipSize: 0.01,
    tickSize: 0.01,
    contractSize: 1,
    minLot: 0.1,
    maxLot: 1000,
    lotStep: 0.1,
    quoteCurrency: 'USD',
    baseCurrency: 'SOL',
    roundingMode: 'DOWN',
  },
  'ADA/USD': {
    symbol: 'ADA/USD',
    assetType: 'crypto_alt',
    priceDecimals: 4,
    pipSize: 0.0001,
    tickSize: 0.0001,
    contractSize: 1000,
    minLot: 1,
    maxLot: 100000,
    lotStep: 1,
    quoteCurrency: 'USD',
    baseCurrency: 'ADA',
    roundingMode: 'DOWN',
  },
  'DOGE/USD': {
    symbol: 'DOGE/USD',
    assetType: 'crypto_alt',
    priceDecimals: 5,
    pipSize: 0.00001,
    tickSize: 0.00001,
    contractSize: 10000,
    minLot: 1,
    maxLot: 1000000,
    lotStep: 1,
    quoteCurrency: 'USD',
    baseCurrency: 'DOGE',
    roundingMode: 'DOWN',
  },
  'DOT/USD': {
    symbol: 'DOT/USD',
    assetType: 'crypto_alt',
    priceDecimals: 3,
    pipSize: 0.001,
    tickSize: 0.001,
    contractSize: 100,
    minLot: 1,
    maxLot: 10000,
    lotStep: 1,
    quoteCurrency: 'USD',
    baseCurrency: 'DOT',
    roundingMode: 'DOWN',
  },
  'AVAX/USD': {
    symbol: 'AVAX/USD',
    assetType: 'crypto_alt',
    priceDecimals: 2,
    pipSize: 0.01,
    tickSize: 0.01,
    contractSize: 10,
    minLot: 0.1,
    maxLot: 10000,
    lotStep: 0.1,
    quoteCurrency: 'USD',
    baseCurrency: 'AVAX',
    roundingMode: 'DOWN',
  },
  'MATIC/USD': {
    symbol: 'MATIC/USD',
    assetType: 'crypto_alt',
    priceDecimals: 4,
    pipSize: 0.0001,
    tickSize: 0.0001,
    contractSize: 1000,
    minLot: 1,
    maxLot: 100000,
    lotStep: 1,
    quoteCurrency: 'USD',
    baseCurrency: 'MATIC',
    roundingMode: 'DOWN',
  },
  'LINK/USD': {
    symbol: 'LINK/USD',
    assetType: 'crypto_alt',
    priceDecimals: 2,
    pipSize: 0.01,
    tickSize: 0.01,
    contractSize: 100,
    minLot: 0.1,
    maxLot: 10000,
    lotStep: 0.1,
    quoteCurrency: 'USD',
    baseCurrency: 'LINK',
    roundingMode: 'DOWN',
  },
  'UNI/USD': {
    symbol: 'UNI/USD',
    assetType: 'crypto_alt',
    priceDecimals: 2,
    pipSize: 0.01,
    tickSize: 0.01,
    contractSize: 100,
    minLot: 0.1,
    maxLot: 10000,
    lotStep: 0.1,
    quoteCurrency: 'USD',
    baseCurrency: 'UNI',
    roundingMode: 'DOWN',
  },
  'LTC/USD': {
    symbol: 'LTC/USD',
    assetType: 'crypto_major',
    priceDecimals: 2,
    pipSize: 0.1,
    tickSize: 0.01,
    contractSize: 1,
    minLot: 0.1,
    maxLot: 1000,
    lotStep: 0.1,
    quoteCurrency: 'USD',
    baseCurrency: 'LTC',
    roundingMode: 'DOWN',
  },
  'BCH/USD': {
    symbol: 'BCH/USD',
    assetType: 'crypto_major',
    priceDecimals: 2,
    pipSize: 0.1,
    tickSize: 0.01,
    contractSize: 1,
    minLot: 0.1,
    maxLot: 1000,
    lotStep: 0.1,
    quoteCurrency: 'USD',
    baseCurrency: 'BCH',
    roundingMode: 'DOWN',
  },
  'ATOM/USD': {
    symbol: 'ATOM/USD',
    assetType: 'crypto_alt',
    priceDecimals: 2,
    pipSize: 0.01,
    tickSize: 0.01,
    contractSize: 100,
    minLot: 0.1,
    maxLot: 10000,
    lotStep: 0.1,
    quoteCurrency: 'USD',
    baseCurrency: 'ATOM',
    roundingMode: 'DOWN',
  },
  'XLM/USD': {
    symbol: 'XLM/USD',
    assetType: 'crypto_alt',
    priceDecimals: 5,
    pipSize: 0.00001,
    tickSize: 0.00001,
    contractSize: 10000,
    minLot: 1,
    maxLot: 1000000,
    lotStep: 1,
    quoteCurrency: 'USD',
    baseCurrency: 'XLM',
    roundingMode: 'DOWN',
  },
  'ALGO/USD': {
    symbol: 'ALGO/USD',
    assetType: 'crypto_alt',
    priceDecimals: 4,
    pipSize: 0.0001,
    tickSize: 0.0001,
    contractSize: 1000,
    minLot: 1,
    maxLot: 100000,
    lotStep: 1,
    quoteCurrency: 'USD',
    baseCurrency: 'ALGO',
    roundingMode: 'DOWN',
  },
  'VET/USD': {
    symbol: 'VET/USD',
    assetType: 'crypto_alt',
    priceDecimals: 5,
    pipSize: 0.00001,
    tickSize: 0.00001,
    contractSize: 100000,
    minLot: 1,
    maxLot: 10000000,
    lotStep: 1,
    quoteCurrency: 'USD',
    baseCurrency: 'VET',
    roundingMode: 'DOWN',
  },
  'NEAR/USD': {
    symbol: 'NEAR/USD',
    assetType: 'crypto_alt',
    priceDecimals: 3,
    pipSize: 0.001,
    tickSize: 0.001,
    contractSize: 100,
    minLot: 0.1,
    maxLot: 10000,
    lotStep: 0.1,
    quoteCurrency: 'USD',
    baseCurrency: 'NEAR',
    roundingMode: 'DOWN',
  },
  'FTM/USD': {
    symbol: 'FTM/USD',
    assetType: 'crypto_alt',
    priceDecimals: 4,
    pipSize: 0.0001,
    tickSize: 0.0001,
    contractSize: 1000,
    minLot: 1,
    maxLot: 100000,
    lotStep: 1,
    quoteCurrency: 'USD',
    baseCurrency: 'FTM',
    roundingMode: 'DOWN',
  },
  'SAND/USD': {
    symbol: 'SAND/USD',
    assetType: 'crypto_alt',
    priceDecimals: 4,
    pipSize: 0.0001,
    tickSize: 0.0001,
    contractSize: 1000,
    minLot: 1,
    maxLot: 100000,
    lotStep: 1,
    quoteCurrency: 'USD',
    baseCurrency: 'SAND',
    roundingMode: 'DOWN',
  },
  'MANA/USD': {
    symbol: 'MANA/USD',
    assetType: 'crypto_alt',
    priceDecimals: 4,
    pipSize: 0.0001,
    tickSize: 0.0001,
    contractSize: 1000,
    minLot: 1,
    maxLot: 100000,
    lotStep: 1,
    quoteCurrency: 'USD',
    baseCurrency: 'MANA',
    roundingMode: 'DOWN',
  },
  'AXS/USD': {
    symbol: 'AXS/USD',
    assetType: 'crypto_alt',
    priceDecimals: 2,
    pipSize: 0.01,
    tickSize: 0.01,
    contractSize: 10,
    minLot: 0.1,
    maxLot: 10000,
    lotStep: 0.1,
    quoteCurrency: 'USD',
    baseCurrency: 'AXS',
    roundingMode: 'DOWN',
  },
  'CRO/USD': {
    symbol: 'CRO/USD',
    assetType: 'crypto_alt',
    priceDecimals: 5,
    pipSize: 0.00001,
    tickSize: 0.00001,
    contractSize: 10000,
    minLot: 1,
    maxLot: 1000000,
    lotStep: 1,
    quoteCurrency: 'USD',
    baseCurrency: 'CRO',
    roundingMode: 'DOWN',
  },
  'APE/USD': {
    symbol: 'APE/USD',
    assetType: 'crypto_alt',
    priceDecimals: 3,
    pipSize: 0.001,
    tickSize: 0.001,
    contractSize: 100,
    minLot: 0.1,
    maxLot: 100000,
    lotStep: 0.1,
    quoteCurrency: 'USD',
    baseCurrency: 'APE',
    roundingMode: 'DOWN',
  },
  'SHIB/USD': {
    symbol: 'SHIB/USD',
    assetType: 'crypto_alt',
    priceDecimals: 8,
    pipSize: 0.00000001,
    tickSize: 0.00000001,
    contractSize: 100000000,
    minLot: 1,
    maxLot: 100000000,
    lotStep: 1,
    quoteCurrency: 'USD',
    baseCurrency: 'SHIB',
    roundingMode: 'DOWN',
  },
  'TRX/USD': {
    symbol: 'TRX/USD',
    assetType: 'crypto_alt',
    priceDecimals: 5,
    pipSize: 0.00001,
    tickSize: 0.00001,
    contractSize: 10000,
    minLot: 1,
    maxLot: 10000000,
    lotStep: 1,
    quoteCurrency: 'USD',
    baseCurrency: 'TRX',
    roundingMode: 'DOWN',
  },
  'ETC/USD': {
    symbol: 'ETC/USD',
    assetType: 'crypto_alt',
    priceDecimals: 2,
    pipSize: 0.01,
    tickSize: 0.01,
    contractSize: 10,
    minLot: 0.1,
    maxLot: 10000,
    lotStep: 0.1,
    quoteCurrency: 'USD',
    baseCurrency: 'ETC',
    roundingMode: 'DOWN',
  },
  
  // ÉNERGIES
  'USOIL': {
    symbol: 'USOIL',
    assetType: 'energy',
    priceDecimals: 2,
    pipSize: 0.01,
    tickSize: 0.01,
    contractSize: 1000, // 1000 barils
    minLot: 0.01,
    maxLot: 100,
    lotStep: 0.01,
    quoteCurrency: 'USD',
    roundingMode: 'DOWN',
  },
  'UKOIL': {
    symbol: 'UKOIL',
    assetType: 'energy',
    priceDecimals: 2,
    pipSize: 0.01,
    tickSize: 0.01,
    contractSize: 1000,
    minLot: 0.01,
    maxLot: 100,
    lotStep: 0.01,
    quoteCurrency: 'USD',
    roundingMode: 'DOWN',
  },
  'NATGAS': {
    symbol: 'NATGAS',
    assetType: 'energy',
    priceDecimals: 3,
    pipSize: 0.001,
    tickSize: 0.001,
    contractSize: 10000,
    minLot: 0.01,
    maxLot: 100,
    lotStep: 0.01,
    quoteCurrency: 'USD',
    roundingMode: 'DOWN',
  },
  
  // ACTIONS US (sélection)
  'AAPL': { symbol: 'AAPL', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'MSFT': { symbol: 'MSFT', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'GOOGL': { symbol: 'GOOGL', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'AMZN': { symbol: 'AMZN', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'META': { symbol: 'META', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'NVDA': { symbol: 'NVDA', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'TSLA': { symbol: 'TSLA', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'AMD': { symbol: 'AMD', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'INTC': { symbol: 'INTC', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'NFLX': { symbol: 'NFLX', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'PYPL': { symbol: 'PYPL', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'ADBE': { symbol: 'ADBE', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'CRM': { symbol: 'CRM', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'CSCO': { symbol: 'CSCO', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'ORCL': { symbol: 'ORCL', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'IBM': { symbol: 'IBM', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'QCOM': { symbol: 'QCOM', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'UBER': { symbol: 'UBER', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'ABNB': { symbol: 'ABNB', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'COIN': { symbol: 'COIN', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'JPM': { symbol: 'JPM', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'BAC': { symbol: 'BAC', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'WFC': { symbol: 'WFC', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'GS': { symbol: 'GS', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'MS': { symbol: 'MS', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'C': { symbol: 'C', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'AXP': { symbol: 'AXP', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'V': { symbol: 'V', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'MA': { symbol: 'MA', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'BLK': { symbol: 'BLK', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'JNJ': { symbol: 'JNJ', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'PFE': { symbol: 'PFE', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'UNH': { symbol: 'UNH', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'XOM': { symbol: 'XOM', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'CVX': { symbol: 'CVX', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'WMT': { symbol: 'WMT', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'HD': { symbol: 'HD', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'DIS': { symbol: 'DIS', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'KO': { symbol: 'KO', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'PEP': { symbol: 'PEP', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'MCD': { symbol: 'MCD', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'NKE': { symbol: 'NKE', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'SBUX': { symbol: 'SBUX', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'BA': { symbol: 'BA', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'CAT': { symbol: 'CAT', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'MMM': { symbol: 'MMM', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'GE': { symbol: 'GE', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'F': { symbol: 'F', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'GM': { symbol: 'GM', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
  'T': { symbol: 'T', assetType: 'stock', priceDecimals: 2, pipSize: 0.01, tickSize: 0.01, contractSize: 1, minLot: 1, maxLot: 10000, lotStep: 1, quoteCurrency: 'USD', roundingMode: 'DOWN' },
};

/**
 * Obtenir la configuration d'un actif
 * @throws Error si l'actif n'est pas configuré
 */
export function getAssetConfig(symbol: string): AssetConfig {
  const config = ASSET_CONFIGS[symbol];
  if (!config) {
    throw new Error(`Configuration manquante pour l'actif: ${symbol}. Veuillez contacter le support.`);
  }
  return config;
}

/**
 * Vérifier si un actif est supporté
 */
export function isAssetSupported(symbol: string): boolean {
  return symbol in ASSET_CONFIGS;
}

/**
 * Obtenir tous les symboles supportés
 */
export function getAllSupportedSymbols(): string[] {
  return Object.keys(ASSET_CONFIGS);
}

/**
 * Obtenir les symboles par type d'actif
 */
export function getSymbolsByType(assetType: AssetType): string[] {
  return Object.values(ASSET_CONFIGS)
    .filter(config => config.assetType === assetType)
    .map(config => config.symbol);
}
